[package]
name = "sd-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
clap = { version = "4.5.20", features = ["derive"] }
log = "0.4.22"
once_cell = "1.20.2"
sd-lib = { path = "../sd-lib" }
